title: Hem Poudyal
logo:  # you can add own logo.
description: iOS Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Hem Poudyal
  image: '/assets/img/imgProfile.jpg'
  job: iOS Engineer
  bio: Passionate in problem solving, Believes in creation, Hungry to learn and improve Codes + Designs
  email: hem.iosdev@gmail.com


# Contact links
contact:
  - name: Github
    link: https://github.com/hempoudyal
  - name: Twitter
    link: https://twitter.com/hempoudyal
  - name: LinkedIn
    link: https://www.linkedin.com/in/hem-poudyal-3b935339/
  - name: Medium
    link: https://medium.com/@poudyalhem


# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: # add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
